name: $bog_mediagram

permissions: write-all

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: hyoo-ru/mam_build@master2
      with:
        package: 'bog/mediagram'
        modules: 'app'

    - name: install SPA fallback
      if: github.ref == 'refs/heads/main'
      run: cp bog/mediagram/app/-/index.html bog/mediagram/app/-/404.html

    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/main'
      with:
        folder: 'bog/mediagram/app/-'
